---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-11-22:56:31
---

local CardVo = require("Game.Modules.Room.Vo.CardVo")
local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.HongJian.Service.HongJianService : Game.Core.Ioc.BaseService
---@field hongJianModel Game.Modules.HongJian.Model.HongJianModel
---@field roleModel Game.Modules.Role.Model.RoleModel
local HongJianService = class("HongJianService",BaseService)

function HongJianService:Ctor()
    nmgr:AddPush(Action.PushHJCardSlot, handler(self,self.OnPushHJCardSlot))
    nmgr:AddPush(Action.PushHJWhoseTurn, handler(self,self.OnPushHJWhoseTurn))
end

function HongJianService:OnPushHJCardSlot(response)
    if self.roleModel.roleId == response.data.clientRoleId then
        self.hongJianModel.cards = {}
        for i = 1, #response.data.cardSlot do
            local card = CardVo.New()
            card:FromJson(response.data.cardSlot[i])
            self.hongJianModel.cards[i] = card
        end
    else

    end
end

function HongJianService:OnPushHJWhoseTurn(response)
    if self.roleModel.roleId == response.data.clientRoleId then
        self.hongJianModel.currTurnDuration = response.data.turnDuration    --本轮持续总时间
        self.hongJianModel.currTurnNum = response.data.turnNum              --当前第几轮
        self.hongJianModel.currTurnRolePos = response.data.roomPos          --本轮出牌人位置
    end
end

return HongJianService
