---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/30 0:02
--- 场景的基类
---


local LuaMonoBehaviour = require('Betel.LuaMonoBehaviour')
---@class Game.Modules.World.Scenes.BaseScene : Betel.LuaMonoBehaviour
---@field unityScene UnityEngine.SceneManagement.Scene
---@field uiCanvas UnityEngine.GameObject
local BaseScene = class("BaseScene",LuaMonoBehaviour)

function BaseScene:Ctor()
    LuaMonoBehaviour.Ctor(self)
    self:Init()
end

function BaseScene:Init()
    vmgr:SetScene(self)
end

function BaseScene:OnEnterScene()

end

function BaseScene:OnExitScene()

end
return BaseScene