---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/18 23:55
---

local LuaMonoBehaviour = require('Betel.LuaMonoBehaviour')

---@class Game.Modules.World.Scenes.SubScene : Betel.LuaMonoBehaviour
---@field New fun(subSceneInfo:SubSceneInfo, unityScene:UnityEngine.SceneManagement.Scene)
---@field unityScene UnityEngine.SceneManagement.Scene
---@field subSceneInfo SubSceneInfo
local SubScene = class("BaseScene",LuaMonoBehaviour)

---@param subSceneInfo SubSceneInfo
---@param unityScene UnityEngine.SceneManagement.Scene
function SubScene:Ctor(subSceneInfo, unityScene)
    LuaMonoBehaviour.Ctor(self)
    self.subSceneInfo = subSceneInfo
    self.unityScene = unityScene
end

function SubScene:Init()
    UnityEngine.SceneManagement.SceneManager.SetActiveScene(self.unityScene)
end

function SubScene:Unload()
    sceneMgr:UnloadSubSceneAsync(self.subSceneInfo.level, function(levelName)

    end)
end

return SubScene