---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-08-13-23:21:39
---

---@class Game.Modules.Newbie.Service.NewbieService : Game.Core.Ioc.BaseService
local BaseService = require("Game.Core.Ioc.BaseService")
local NewbieService = class("NewbieService",BaseService)

function NewbieService:Ctor()
    
end

return NewbieService
