---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/3/13 23:47
---


local CardSlot = require("Game.Modules.Common.Utils.CardSlot")
---@class Game.Modules.HongJian.View.CardSlot_HJ : Game.Modules.Common.Utils.CardSlot
---@field public New function<deskPosObj:UnityEngine.GameObject, cards:table<number, Game.Modules.Room.Vo.CardVo>, showFront:boolean, selectable:boolean>
local CardSlot_HJ = class("CardSlot_HJ",CardSlot)

function CardSlot_HJ:Ctor(deskPosObj, cards, showFront, selectable)
    CardSlot_HJ.super.Ctor(deskPosObj, cards, showFront, selectable);
end

return CardSlot_HJ