---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-11-22:56:14
---

local CardSlot = require("Game.Modules.Common.Utils.CardSlot")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.HongJian.View.HongJianSceneMdr : Game.Core.Ioc.BaseMediator
---@field hongJianModel Game.Modules.HongJian.Model.HongJianModel
---@field hongJianService Game.Modules.HongJian.Service.HongJianService
---@field lobbyService Game.Modules.Lobby.Service.LobbyService
---@field robotModel Game.Modules.Robot.Model.RobotModel
---@field roomModel Game.Modules.Room.Model.RoomModel
---@field roleModel Game.Modules.Role.Model.RoleModel
local HongJianSceneMdr = class("HongJianSceneMdr",BaseMediator)


function HongJianSceneMdr:OnInit()
    self:CreateRoom_HJ()--创建红尖房间

    self.posSlot = {}
end

--创建红尖房间
function HongJianSceneMdr:CreateRoom_HJ()
    self.lobbyService:CreateRoom(GameName.Hong_Jian,"1vs1",function ()
        --房间创建成功，自己首先进入房间
    end,function ()
        --log("匹配失败")
    end)
end

function HongJianSceneMdr:RegisterListeners()
    self:AddPush(Action.PushRoomInfo, handler(self,self.OnPushRoomInfo))
    self:AddPush(Action.PushHJCardSlot, handler(self,self.OnPushHJCardSlot))
end

function HongJianSceneMdr:OnPushRoomInfo(response)
    if self.roleModel.roleId == response.data.clientRoleId then
        if self.roomModel.room.game == GameName.Hong_Jian then
            vmgr:LoadView(ViewConfig.SampleRoom)
        end
    end
end

function HongJianSceneMdr:OnPushHJCardSlot(response)
    if self.roleModel.roleId == response.data.clientRoleId then
        vmgr:LoadView(ViewConfig.HongJianConsole)
        vmgr:LoadView(ViewConfig.RoomDesk)
        self.posSlot[DeskPos.South] = self:CreateCardSlot(DeskPos.South,self.hongJianModel.cards,true,true)
    else
        --其他玩家
        local robotClient = self.robotModel.robotClientMap[response.data.clientRoleId]
        local otherPos = self.roomModel:CalculateDeskPosition(self.roomModel.myRoomRoleInfo.roomPos)
        local deskPos = otherPos[robotClient.roomRole.roomPos]
        self.posSlot[deskPos] = self:CreateCardSlot(deskPos,robotClient.cards,true, false)
    end
end


function HongJianSceneMdr:CreateCardSlot(deskPos, cards, showFront, selectable)
    local deskPosObj = GameObject.Find(deskPos)
    local slot = CardSlot.New(deskPosObj, cards, showFront, selectable)
    return slot
end

return HongJianSceneMdr
