---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/29 23:35
---

require "Game.Config.ViewConfig"
require "Game.Config.WorldConfig"
require "Game.Config.Card.CardDefine"
log("Global config has all require")