---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-04-21-23:21:22
---

local RoomDeskRomeItem = require("Game.Modules.Room.View.RoomDeskRomeItem")
local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Room.View.RoomDeskMdr : Game.Core.Ioc.BaseMediator
---@field roomModel Game.Modules.Room.Model.RoomModel
---@field roomService Game.Modules.Room.Service.RoomService
---@field roleItemMap table<number,Game.Modules.Room.View.RoomDeskRomeItem>
local RoomDeskMdr = class("RoomDeskMdr",BaseMediator)

function RoomDeskMdr:OnInit()

    self.roleItemMap = {}
    self:InitRoleList()
end

function RoomDeskMdr:RegisterListeners()
    self:AddPush(Action.PushHJWhoseTurn, handler(self,self.OnPushHJWhoseTurn))
end

function RoomDeskMdr:InitRoleList()
    local roleList = self.roomModel.room.roleList
    for i = 1, #roleList do
        local posObj = self.gameObject:FindChild("RoleList/Pos" .. i)
        local roleItemObj = Instantiate(self.gameObject:FindChild("RoleItem"), posObj.transform)
        roleItemObj:ResetTransform()
        self.roleItemMap[roleList[i].roomPos] = self:CreateRoleItem(roleItemObj, roleList[i], i)
    end
end

---@param itemObj UnityEngine.GameObject
---@param roleData Game.Modules.Room.Vo.RoomRoleVo
---@return Game.Modules.Room.View.RoomDeskRomeItem
function RoomDeskMdr:CreateRoleItem(itemObj,data,index)
    itemObj:SetActive(true)
    local itemRender = RoomDeskRomeItem.New(itemObj)
    itemRender:UpdateItem(data, index)
    return itemRender
end

function RoomDeskMdr:OnPushHJWhoseTurn(response)
    --if self.roleModel.roleId == response.data.clientRoleId then
        for i, roleItem in pairs(self.roleItemMap) do
            if response.data.roomPos + 1 == roleItem.data.roomPos then
                local roleItem = self.roleItemMap[response.data.roomPos + 1]
                roleItem:OnTurnEnter(response.data)
            else
                roleItem:OnTurnExit()
            end
        end
    --end
end

return RoomDeskMdr
