---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/4/21 23:51
---

local ImageHelper = require("Game.Modules.Common.View.ImageHelper")
local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Room.View.RoomDeskRomeItem : Betel.UI.ListItemRenderer
---@field New fun(gameObject:UnityEngine.GameObject):Game.Modules.Room.View.RoomDeskRomeItem
local RoomDeskRomeItem = class("Game.Modules.Room.View.RoomDeskRomeItem",ListItemRenderer)

function RoomDeskRomeItem:Ctor(gameObject)
    RoomDeskRomeItem.super.Ctor(self,gameObject)
    self:AddLuaMonoBehaviour(gameObject, "RoomDeskRomeItem")
    self.nameText = self.gameObject:FindChild("Name"):GetText()
    self.stateText = self.gameObject:FindChild("State"):GetText()
    self.turnTimeText = self.gameObject:FindChild("TurnTime"):GetText()
end

---@param data RoomRoleVo
function RoomDeskRomeItem:UpdateItem(data, index)
    RoomDeskRomeItem.super.UpdateItem(self,data, index)
    self.nameText.text = data.roleName
    self.stateText.text = data.roleState
    self.turnTimeText.text = ""
    ImageHelper.SetHeadIcon(self.gameObject:FindChild("Icon"), data.headIcon)
end

function RoomDeskRomeItem:OnTurnEnter(data)
    self.data.turnDuration = data.turnDuration
    self.startTime = Time.time
end

function RoomDeskRomeItem:Update()
    if self.data and self.data.turnDuration and self.data.turnDuration > 0 then
        local leftTime = (self.data.turnDuration / 1000) - (Time.time - self.startTime)
        self.turnTimeText.text = leftTime > 0 and Mathf.Floor(leftTime) or ""
    end
end

function RoomDeskRomeItem:OnTurnExit()
    self.data.turnDuration = 0
    self.turnTimeText.text = ""
end

function RoomDeskRomeItem:OnDestroy()

end

return RoomDeskRomeItem