---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/31 23:11
---

local ListItemRenderer = require("Betel.UI.ListItemRenderer")
---@class Game.Modules.Room.View.SimpleRoleItem: Betel.UI.ListItemRenderer
local SimpleRoleItem = class("Game.Modules.Room.View.SimpleRoleItem",ListItemRenderer)

local headIconUrl = "Textures/HeadIcon/%s.jpg"
---@param gameObject UnityEngine.GameObject
function SimpleRoleItem:Ctor(gameObject)
    SimpleRoleItem.super.Ctor(self,gameObject)
end

---@param data RoomRoleVo
function SimpleRoleItem:UpdateItem(data, index)
    if data then
        self.gameObject:GetText("Text").text = data.roleName
        self.gameObject:GetText("State").text = data.roleName
        ImageHelper.SetHeadIcon(self.gameObject:FindChild("Icon"), data.headIcon)
    else
        self.gameObject:GetText("Text").text = "<N/A>"
        self.gameObject:GetText("State").text = "<N/A>"
        self.gameObject:SetImageAlpha(0,"Icon")
    end
end

function SimpleRoleItem:OnDestroy()

end

return SimpleRoleItem