---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-27-00:43:04
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Lobby.View.LobbySceneMdr : Game.Core.Ioc.BaseMediator
---@field lobbyModel Game.Modules.Lobby.Model.LobbyModel
---@field lobbyService Game.Modules.Lobby.Service.LobbyService
---@field roleModel Game.Modules.Role.Model.RoleModel
local LobbySceneMdr = class("LobbySceneMdr",BaseMediator)

function LobbySceneMdr:OnInit()
    --游戏主菜单
    vmgr:LoadView(ViewConfig.LobbyMainMenu)
end

function LobbySceneMdr:RegisterListeners()
    self:AddPush(Action.PushRoomInfo, handler(self,self.OnPushRoomInfo))
end

function LobbySceneMdr:OnPushRoomInfo(response)
    if self.roleModel.roleId == response.data.clientRoleId then
        vmgr:LoadView(ViewConfig.SampleRoom)
    end
end

return LobbySceneMdr
