---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-28-23:33:46
---

local BaseMediator = require("Game.Core.Ioc.BaseMediator")
---@class Game.Modules.Lobby.View.LobbyMainMenuMdr : Game.Core.Ioc.BaseMediator
---@field lobbyModel Game.Modules.Lobby.Model.LobbyModel
---@field lobbyService Game.Modules.Lobby.Service.LobbyService
---@field roleModel Game.Modules.Role.Model.RoleModel
local LobbyMainMenuMdr = class("LobbyMainMenuMdr",BaseMediator)

function LobbyMainMenuMdr:OnInit()

end

function LobbyMainMenuMdr:On_Click_BtnMatch()
    self.lobbyService:JoinMatch(GameName.Hong_Jian,"1vs1",function ()
        --log("正在匹配")
    end,function ()
        --log("匹配失败")
    end)
end

function LobbyMainMenuMdr:On_Click_BtnCreate()
    self.lobbyService:CreateRoom(GameName.Hong_Jian,"1vs1",function ()
        --房间创建成功，自己首先进入房间
    end,function ()
        --log("匹配失败")
    end)
end


function LobbyMainMenuMdr:On_Click_BtnGame1()
    self:EnterGame_HJ()
end

function LobbyMainMenuMdr:On_Click_BtnGame2()
    self:EnterGame_HJ()
end

function LobbyMainMenuMdr:EnterGame_HJ()
    World.EnterScene(WorldConfig.Room_HJ)
end

return LobbyMainMenuMdr
