---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/24 22:11
---

local BornWave = require("Game.Modules.Battle.Behaviors.BornWave")
local BaseBehavior = require('Game.Modules.Common.Behavior.BaseBehavior')

---@class Game.Modules.Battle.Behaviors.BornArea : Game.Modules.Common.Behavior.BaseBehavior
---@field New fun() : Game.Modules.Common.Behavior.BornArea
---@field areaInfo AreaInfo
---@field points table<number, UnityEngine.Vector3>
---@field waves table<number, Game.Modules.Battle.Behaviors.BornWave>
---@field areaRect UnityEngine.Rect
local BornArea = class("Game.Modules.Battle.Behaviors.BornWave",BaseBehavior)

---@param areaInfo AreaInfo
function BornArea:Ctor(areaInfo)
    BornArea.super.Ctor(self)
    self.areaInfo = areaInfo
    self.waves = {}

    local pos = World.points[self.areaInfo.bornPos]
    self.areaRect = Tools3D.GetAreaNodeRect(World.grid, pos, self.areaInfo.rangeX, self.areaInfo.rangeY)
    self.points = Tools3D.GetRectRandomPos(pos, self.areaRect, World.grid.nodeRadius)
end

function BornArea:Refresh()
    for i = 1, #self.areaInfo.waves do
        local wave = BornWave.New(self.areaInfo, self.areaInfo.waves[i], self.points)
        table.insert(self.waves, wave)
        wave:Refresh()
        wave:Active()
    end
end

--获取可以到达的格子
---@param src Game.Modules.Battle.Items.Monster
function BornArea:GetReachableNode(src)
    local soonGrid = Tools3D.GetRandomNeighboursNode(World.grid, src)
    if soonGrid ~= nil and self:isEmptyGrid(soonGrid) then
        return soonGrid
    else
        return nil
    end
end

---@param node AStar.Node
---@return
function BornArea:isEmptyGrid(node)
    for i = 1, #self.waves do
        local wave = self.waves[i]
        for j = 1, #wave.monsterList do
            local monster = wave.monsterList[j]
            if Tools3D.isEqualNode(monster.node, node) or Tools3D.isEqualNode(monster.soonNode, node) then
                return false
            end
        end
    end
    return true
end

function BornArea:Active()
    for i = 1, #self.waves do
        local wave = self.waves[i]
        wave:Refresh()
    end
end


return BornArea