---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/21 22:48
---

local Monster = require("Game.Modules.Battle.Items.Monster")
local BaseBehavior = require('Game.Modules.Common.Behavior.BaseBehavior')

---@class Game.Modules.Battle.Behaviors.BornWave : Game.Modules.Common.Behavior.BaseBehavior
---@field waveInfo WaveInfo
---@field areaInfo AreaInfo
---@field points table<number, UnityEngine.Vector3>
---@field monsterList table<number, Game.Modules.Battle.Items.Monster>
local BornWave = class("Game.Modules.Battle.Behaviors.BornArea",BaseBehavior)

---@param areaInfo AreaInfo
---@param waveInfo WaveInfo
---@param points table<number, UnityEngine.Vector3>
function BornWave:Ctor(areaInfo, waveInfo, points)
    BornWave.super.Ctor(self)
    self.areaInfo = areaInfo
    self.waveInfo = waveInfo
    self.points = points
    self.monsterList = {}
end

function BornWave:Refresh()
    self:DoRefresh()
end

function BornWave:Active()
    self:ForEach(Handler.New(function(monster)
        monster:SetBehaviorEnable(true)
    end))
end

function BornWave:Visible(visible)
    self:ForEach(Handler.New(function(monster)
        monster:SetRenderObjVisible(visible)
    end))
end

function BornWave:DoRefresh()
    local count = 1
    for i = 1, #self.waveInfo.borns do
        local bornInfo = self.waveInfo.borns[i]
        local num = math.random(bornInfo.minNum, bornInfo.maxNum)
        for n = 1, num do
            local monster = Monster.New(AvatarConfig.Clone(bornInfo.avatarName))
            self.monsterList[count] = monster
            local rx = math.random(-1.0,1.0)
            local rz = math.random(-1.0,1.0)
            monster.transform.position = self.points[self.areaInfo.bornPos] + Vector3.New(rx, self.points[self.areaInfo.bornPos].y,rz)
            count = count + 1
        end
    end
end

---@param func Handler
function BornWave:ForEach(func)
    for i = 1, #self.monsterList do
        func:Execute(self.monsterList[i])
    end
end

---@param monster Game.Modules.Battle.Items.Monster
function BornWave:DisposeMonster(monster)
    monster:Dispose()
end

function BornWave:Dispose()
    BornWave.super.Dispose(self)
    self:ForEach(Handler.New(self.DisposeMonster, self))
end

return BornWave