---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/21 22:58
---

local HeroBehavior = require('Game.Modules.Battle.Behaviors.HeroBehavior')

---@class Game.Modules.Battle.Behaviors.MainHeroBehavior : Game.Modules.Battle.Behaviors.HeroBehavior
---@field New fun() : Game.Modules.Battle.Behaviors.MainHeroBehavior
local MainHeroBehavior = class("Game.Modules.Battle.Behaviors.MainHeroBehavior",HeroBehavior)

---@param hero Game.Modules.Battle.Items.MainHero
function MainHeroBehavior:Ctor(hero)
    MainHeroBehavior.super.Ctor(self, hero)
    local s_id = 1
    self:AppendState(function()
        coroutine.start(function()
            coroutine.wait(1)
            print("s_id:" .. s_id)
            self:NextState()
        end)
    end)
    self:AppendState(function()
        coroutine.start(function()
            coroutine.wait(1)
            print("AvatarBehavior is over s_id:" .. s_id)
            s_id = s_id + 1
            self:NextState()
        end)
    end)
end

function MainHeroBehavior:Dispose()
    MainHeroBehavior.super.Dispose(self)
end

return MainHeroBehavior