---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/22 22:43
---

local AvatarBehavior = require('Game.Modules.Battle.Behaviors.AvatarBehavior')

---@class Game.Modules.Battle.Behaviors.HeroBehavior : Game.Modules.Battle.Behaviors.AvatarBehavior
---@field New fun() : Game.Modules.Battle.Behaviors.HeroBehavior
---@field hero Game.Modules.Battle.Items.Hero
local HeroBehavior = class("Game.Modules.Battle.Behaviors.HeroBehavior",AvatarBehavior)

---@param hero Game.Modules.Battle.Items.Hero
function HeroBehavior:Ctor(hero)
    HeroBehavior.super.Ctor(self, hero)
    self.hero = hero
    local s_id = 1
    self:AppendState(function()
        coroutine.start(function()
            coroutine.wait(1)
            print("s_id:" .. s_id)
            self:NextState()
        end)
    end)
    self:AppendState(function()
        coroutine.start(function()
            coroutine.wait(1)
            print("AvatarBehavior is over s_id:" .. s_id)
            s_id = s_id + 1
            self:NextState()
        end)
    end)
end

function HeroBehavior:Dispose()
    HeroBehavior.super.Dispose(self)
end

return HeroBehavior