---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/22 22:43
---

local BaseBehavior = require('Game.Modules.Common.Behavior.BaseBehavior')
local AvatarBehavior = require('Game.Modules.Battle.Behaviors.AvatarBehavior')

---@class Game.Modules.Battle.Behaviors.MonsterBehavior : Game.Modules.Battle.Behaviors.AvatarBehavior
---@field New fun() : Game.Modules.Battle.Behaviors.MonsterBehavior
---@field hero Game.Modules.Battle.Items.Hero
local MonsterBehavior = class("Game.Modules.Battle.Behaviors.MonsterBehavior",AvatarBehavior)

---@param hero Game.Modules.Battle.Items.Hero
function MonsterBehavior:Ctor(hero)
    MonsterBehavior.super.Ctor(self, hero)
    self.hero = hero
    local s_id = 1
    self:AppendState(function()
        coroutine.start(function()
            coroutine.wait(1)
            print("s_id:" .. s_id)
            self:NextState()
        end)
    end)
    self:AppendState(function()
        coroutine.start(function()
            coroutine.wait(1)
            print("AvatarBehavior is over s_id:" .. s_id)
            s_id = s_id + 1
            self:NextState()
        end)
    end)
end

function MonsterBehavior:Dispose()
    MonsterBehavior.super.Dispose(self)
end

return MonsterBehavior