---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-11-22:56:29
---

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.HongJian.Model.HongJianModel : Game.Core.Ioc.BaseModel
---@field hongJianService Game.Modules.HongJian.Service.HongJianService
---@field cards table<number, Game.Modules.Room.Vo.CardVo>
local HongJianModel = class("HongJianModel",BaseModel)

function HongJianModel:Ctor()
    
end

return HongJianModel
