---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-28-23:25:17
---

local BaseService = require("Game.Core.Ioc.BaseService")
---@class Game.Modules.Lobby.Service.LobbyService : Game.Core.Ioc.BaseService
---@field lobbyModel Game.Modules.Lobby.Model.LobbyModel
---@field roomModel Game.Modules.Room.Model.RoomModel
---@field roleModel Game.Modules.Role.Model.RoleModel
local LobbyService = class("LobbyService",BaseService)

function LobbyService:Ctor()

end

function LobbyService:JoinMatch(game, gameMode, callback, failCallback)
    NetModal.Show()
    self:JsonRequest(Action.JoinMatch, {self.roleModel.roleId, game, gameMode }, function(data)
        NetModal.Hide()
        callback(data)
    end, function (data)
        NetModal.Hide()
        failCallback(data)
    end)
end


function LobbyService:CreateRoom(game, gameMode, callback, failCallback)
    NetModal.Show()
    self:JsonRequest(Action.CreateRoom, {self.roleModel.roleId, game, gameMode,3}, function(data)
        NetModal.Hide()
        self.roomModel.room = data
        self:EnterRoom(self.roomModel.room.id)
        callback(data)
        Tips.Show("Match Successful!")
    end, function (data)
        NetModal.Hide()
        failCallback(data)
    end)
end

function LobbyService:EnterRoom(roomId)
    NetModal.Show()
    self:JsonRequest(Action.EnterRoom, {self.roleModel.roleId, roomId, 0, false}, function(data)
        NetModal.Hide()
    end, function (data)
        NetModal.Hide()
    end)
end



return LobbyService
