---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-01-28-23:25:19
---

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.Lobby.Model.LobbyModel : Game.Core.Ioc.BaseModel
---@field lobbyService Game.Modules.Lobby.Service.LobbyService
local LobbyModel = class("LobbyModel",BaseModel)

function LobbyModel:Ctor()
    
end

return LobbyModel
