---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/21 22:49
---

local RenderItem = require('Game.Modules.Battle.Items.RenderItem')

---@class Game.Modules.Battle.Items.Avatar : Game.Modules.Battle.Items.RenderItem
---@field renderObj UnityEngine.GameObject
local Avatar = class("Game.Modules.Battle.Items.Avatar",RenderItem)

function Avatar:Ctor(sceneItemInfo)
    Avatar.super.Ctor(self, sceneItemInfo)
end

function Avatar:Dispose()
    Avatar.super.Dispose(self)
end

return Avatar