---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/21 22:49
---

local RenderItem = require('Game.Modules.Battle.Items.RenderItem')

---@class Game.Modules.Battle.Items.Avatar : Game.Modules.Battle.Items.RenderItem
---@field avatarInfo AvatarInfo
---@param behavior Game.Modules.Battle.Behaviors.AvatarBehavior
local Avatar = class("Game.Modules.Battle.Items.Avatar",RenderItem)

---@param avatarInfo AvatarInfo
function Avatar:Ctor(avatarInfo)
    Avatar.super.Ctor(self, avatarInfo)
    self.avatarInfo = avatarInfo
end

---@param enable boolean
function Avatar:SetBehaviorEnable(enable)

end

function Avatar:Dispose()
    Avatar.super.Dispose(self)
end

return Avatar