---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/21 22:58
---

local Avatar = require('Game.Modules.Battle.Items.Avatar')

---@class Game.Modules.Battle.Items.Hero : Game.Modules.Battle.Items.Avatar
local Hero = class("Game.Modules.Battle.Items.Hero",Avatar)

function Hero:Ctor(sceneItemInfo)
    Hero.super.Ctor(self, sceneItemInfo)
end

function Hero:Dispose()
    Hero.super.Dispose(self)
end

return Hero