---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/5/21 22:58
---

local Avatar = require('Game.Modules.Battle.Items.Avatar')

---@class Game.Modules.Battle.Items.Monster : Game.Modules.Battle.Items.Avatar
---@param monsterInfo MonsterInfo
---@param behavior Game.Modules.Battle.Behaviors.MonsterBehavior
local Monster = class("Game.Modules.Battle.Items.Hero",Avatar)

---@param monsterInfo MonsterInfo
function Monster:Ctor(monsterInfo)
    Monster.super.Ctor(self, monsterInfo)
    self.monsterInfo = monsterInfo
end

function Monster:OnLoadedRenderObj()
    Monster.super.OnLoadedRenderObj(self)
    --self.behavior = MainHeroBehavior.New(self.gameObject)
    --self:SetRenderObjVisible(false)
end


---@param enable boolean
function Monster:SetBehaviorEnable(enable)
    if self.behavior then
        self.behavior:Dispose()
    end
    if enable then
        self.behavior = MainHeroBehavior.New(self.gameObject)
        self.behavior:Start()
    end
end

function Monster:Dispose()
    Monster.super.Dispose(self)
end

return Monster