---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-05-22:38:37
---

---@class RobotClient 机器人客户端
---@field id string
---@field roomRole Game.Modules.Room.Vo.RoomRoleVo
---@field room Game.Modules.Room.Vo.RoomVo
---@field cards table<number, Game.Modules.Room.Vo.CardVo>

local BaseModel = require("Game.Core.Ioc.BaseModel")
---@class Game.Modules.Robot.Model.RobotModel : Game.Core.Ioc.BaseModel
---@field robotService Game.Modules.Robot.Service.RobotService
---@field robotClientMap table<string, RobotClient>
local RobotModel = class("RobotModel",BaseModel)

function RobotModel:Ctor()
    self.robotCounter = 1;
    self.robotClientMap = {};
end

---@return RobotClient
function RobotModel:CreateRobotClient()
    local robotClient = {}; ---@type RobotClient
    robotClient.id = "robot_" .. self.robotCounter;
    local role = {}; ---@type Game.Modules.Room.Vo.RoomRoleVo
    role.roleState = RoomRoleState.UnReady;
    role.id = robotClient.id;
    role.roleName = robotClient.id;
    role.sex = math.random(0,1);
    role.headIcon = math.random(1,6);
    role.isRobot = true;
    robotClient.roomRole = role;
    self.robotClientMap[robotClient.id] = robotClient;
    self.robotCounter = self.robotCounter + 1
    return robotClient;
end

return RobotModel
