---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-08-13-23:21:37
---

---@class Game.Modules.Newbie.Model.NewbieModel : Game.Core.Ioc.BaseModel
local BaseModel = require("Game.Core.Ioc.BaseModel")
local NewbieModel = class("NewbieModel",BaseModel)

function NewbieModel:Ctor()
    
end

return NewbieModel
