---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-05-23:59:17
---

local CardBaseVo = require("Game.Config.Card.CardBaseVo")
---@class Game.Modules.Room.Vo.CardVo : Game.Config.Card.CardBaseVo

local CardVo = class("Game.Modules.Room.Vo.CardVo",CardBaseVo)

function CardVo:Ctor()
    
end

return CardVo
