---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-05-23:59:04
---

local BaseVo = require("Game.Core.BaseVo")
---@class Game.Modules.Room.Vo.RoomVo : Game.Core.BaseVo
---@field id number
---@field game string
---@field gameMode string
---@field roleList table<number, Game.Modules.Room.Vo.RoomRoleVo>
local RoomVo = class("Game.Modules.Room.Vo.RoomVo",BaseVo)

function RoomVo:Ctor()
    
end

function RoomVo:UpdateState(pos,roleState)
    local role = self.roleList[pos]
    role.roleState = roleState
end

function RoomVo:AllUpdateState(roleState)
    for i = 1, #self.roleList do
        local role = self.roleList[i]
        role.roleState = roleState
    end
end

function RoomVo:isAllState(roleState)
    for i = 1, #self.roleList do
        local role = self.roleList[i]
        if role and role.roleState ~= roleState then
            return false
        end
    end
    return true
end

return RoomVo
