---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2019-03-05-23:59:13
---

local BaseVo = require("Game.Core.BaseVo")
---@class Game.Modules.Room.Vo.RoomRoleVo : Game.Core.BaseVo
---@field id string
---@field roleName string
---@field sex number
---@field headIcon number
---@field roomPos number
---@field roleState string
local RoomRoleVo = class("Game.Modules.Room.Vo.RoomRoleVo",BaseVo)

function RoomRoleVo:Ctor()
    
end

return RoomRoleVo
